linters:
  enable-all: true
  disable:
    - dupl
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - wsl
    - deadcode # deprecated
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - nosnakecase # deprecated
    - rowserrcheck # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - wastedassign # deprecated

issues:
  exclude-rules:
    - path: main.go
      linters:
        - gomnd
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - testpackage
