linters-settings:
  depguard:
    rules:
      main:
        files:
          - "!$test"
        allow:
          - $gostd
          - "github.com/edgelaboratories/fusion"
          - "github.com/fatih/color"
          - "github.com/gookit/config/v2"
          - "github.com/spf13/cobra"

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/edgelaboratories/fusion)

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - wsl
    # deprecated
    - rowserrcheck
    - tenv
    - wastedassign

issues:
  exclude-rules:
    - path: main.go
      linters:
        - gomnd
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - testpackage
